### ISSUE TITLE
Bad `mapfile` Flag '-d:` & Missing `server` Definition Check 

### ISSUE THREAD

**Issue by timnolte** [forumone/artifact-push-buildkite-plugin#1]
https://github.com/forumone/artifact-push-buildkite-plugin/blob/ab307252ba6d873ef4ee298d8c5eee332be7061e/lib/ssh.bash#L23-L25

The [Bash documentation](https://www.gnu.org/software/bash/manual/html_node/Bash-Builtins.html) indicates that `-d`, not `-d:` is a valid flag, however the error returned seems to indicate that `-d` isn't even an option. I'm not sure if this is actually using the bash shell for the `mapfile` call.

Additionally, it seems that there is no validation of the `server` variable which is then causing the "unbound variable" error on line 25.

**Comment by timnolte** [comment]
@gustavderdrache @slucero FYI. Hit this issue when attempting to use the plugin for a Pantheon deployment.

**Comment by gustavderdrache** [comment]
I've confirmed the cause. Amazon Linux 2 uses Bash v4.2, which doesn't support some of these options. I'm changing the test harness to run 4.2 and will be fixing the issues it covers.
