### ISSUE TITLE
SSH Keyscan Not Working for Pantheon Deployments

### ISSUE THREAD

**Issue by timnolte** [forumone/artifact-push-buildkite-plugin#4]
Example `pipeline.yml`: https://github.com/forumone/devops-playground-wp/blob/feature/Pipeline-Extract-Pantheon/.buildkite/pipeline.yml
Pantheon Deployment Failure: https://buildkite.com/forum-one/devops-playground-wp/builds/56#7cec2a9b-f0d9-4611-a682-128e052d54e5/172-177

**Comment by traverus** [comment]
Thank you Stephen and Alex!
